version: '3.1'

services:
  macal-be:
    build:
      context: ./macronutrients-calculator-be
    container_name: macal-be
    # env_file:
    #   - ./macronutrients-calculator-be/.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - macal-network

  postgres:
    image: postgres
    container_name: macal-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: macal
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - macal-network

  macal-fe:
    build:
      context: ./macronutrients-calculator-fe
    container_name: macal-fe
    ports:
      - "3000:3000"
    depends_on:
      - macal-be
    networks:
      - macal-network

volumes:
  postgres-data:

networks:
  macal-network: